 
# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0005_applicationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apnsdevice',
            name='registration_id',
            field=models.CharField(max_length=200, verbose_name='Registration ID'),
        ),
    ]
